apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  namespace: default
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: pv1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
