apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
    spec:
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: pvc2
      containers:
        - name: network-multitool
          image: wbitt/network-multitool
          env:
            - name: HTTP_PORT
              value: "8080"
          ports:
            - containerPort: 8080
              name: multi-port
          volumeMounts:
            - mountPath: /opt
              name: nfs-volume
