apiVersion: v1
kind: Pod
metadata:
  name: multitool-test
  namespace: default
spec:
  containers:
    - name: multitool-test
      image: wbitt/network-multitool
      env:
        - name: HTTP_PORT
          value: "1180"
      ports:
        - containerPort: 1180
          name: http-port
