apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-svc
spec:
  type: NodePort
  selector:
    app: nginx-multitool
  ports:
    - name: nginx
      protocol: TCP
      port: 9001
      targetPort: http
      nodePort: 30001
    - name: multitool
      protocol: TCP
      port: 9002
      targetPort: multi-port
      nodePort: 30002
